apiVersion: v1
kind: ConfigMap
metadata:
  name: esalq-postgres-config
  labels:
    app: esalq-postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: [DEFINIR_SENHA_POSTGRES]